sudo: required

dist: trusty

language: cpp

compiler:
  - clang
  - gcc

install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-linux.tar.gz -O /tmp/premake5.tar.gz
  - tar -zxvf /tmp/premake5.tar.gz
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz -O /tmp/libsodium.tar.gz
  - pushd .
  - cd /tmp
  - tar -zxvf /tmp/libsodium.tar.gz
  - cd libsodium-1.0.10
  - ./configure
  - make
  - sudo make install
  - popd
  - wget https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.1.5.tar.gz -O /tmp/mbedtls.tar.gz
  - pushd .
  - cd /tmp
  - tar -zxvf mbedtls.tar.gz
  - cd mbedtls-mbedtls-2.1.5
  - cmake .
  - make
  - sudo make install
  - popd
  - sudo ldconfig
  - ./premake5 gmake

script: make all
